name: Publish Packages

on:
  release:
    types: [created]

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.8

      - id: set-matrix
        run: echo "::set-output name=matrix::{\"packages\":$(pnpm -s list-packages)}"

  build:
    needs: packages
    strategy:
      matrix: ${{ fromJson(needs.packages.outputs.matrix) }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.8

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          scope: '@microeinhundert'
          cache: pnpm

      - name: Install
        run: pnpm install --filter=${{ matrix.package }}

      - name: Lint
        run: pnpm turbo run lint --filter=${{ matrix.package }}

      - name: Build
        run: pnpm turbo run build --filter=${{ matrix.package }}

      - name: Publish
        run: pnpm publish --no-git-checks --filter "${{ matrix.package }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
