name: Publish Package
on:
  release:
    types: [created]
jobs:
  publish-radonis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@microeinhundert'
      - name: Install monorepo dev dependencies
        run: npm install --include=dev
      - name: Install radonis dependencies
        run: npm install --include=prod --workspace packages/radonis
      - name: Publish radonis on npm 📦
        run: npm publish --access public --workspace packages/radonis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-radonis-server:
    runs-on: ubuntu-latest
    needs: [publish-radonis]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@microeinhundert'
      - name: Install monorepo dev dependencies
        run: npm install --include=dev
      - name: Install radonis-server dependencies
        run: npm install --include=prod --workspace packages/radonis-server
      - name: Publish radonis-server on npm 📦
        run: npm publish --access public --workspace packages/radonis-server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

