name: Publish Packages

on:
  release:
    types: [created]

jobs:
  publish:
      name: Build
      timeout-minutes: 15
      runs-on: ubuntu-latest
      env:
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.32.8

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            scope: '@microeinhundert'
            cache: pnpm

        - name: Install dependencies
          run: pnpm install

        - name: Lint packages
          run: pnpm turbo run lint

        - name: Build packages
          run: pnpm turbo run build

        - name: Publish packages
          run: pnpm publish -r
